// This file is generated by RustQ. Do not edit by hand.

impl rustler::Encoder for EncodedLintDiagnostic<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[atoms::message().encode(env), atoms::name().encode(env)],
                &[self.message.encode(env), self.name.encode(env)],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedSfcError<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        let mut keys = vec![atoms::message().encode(env)];
        let mut values = vec![self.message.encode(env)];
        if let Some(value) = self.code.as_ref() {
            keys.push(atoms::code().encode(env));
            values.push(value.encode(env));
        }
        Term::map_from_arrays(env, &keys, &values).unwrap()
    }
}
impl rustler::Encoder for EncodedTemplateBlock<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::content().encode(env),
                    atoms::lang().encode(env),
                    atoms::loc().encode(env),
                    atoms::attrs().encode(env),
                ],
                &[
                    self.0.content.as_ref().encode(env),
                    self.0.lang.as_deref().encode(env),
                    loc_to_term(env, &self.0.loc),
                    attrs_to_term(env, &self.0.attrs),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedScriptBlock<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::content().encode(env),
                    atoms::lang().encode(env),
                    atoms::setup().encode(env),
                    atoms::loc().encode(env),
                    atoms::attrs().encode(env),
                ],
                &[
                    self.0.content.as_ref().encode(env),
                    self.0.lang.as_deref().encode(env),
                    self.0.setup.encode(env),
                    loc_to_term(env, &self.0.loc),
                    attrs_to_term(env, &self.0.attrs),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedStyleBlock<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::content().encode(env),
                    atoms::lang().encode(env),
                    atoms::scoped().encode(env),
                    atoms::module().encode(env),
                    atoms::loc().encode(env),
                    atoms::attrs().encode(env),
                ],
                &[
                    self.0.content.as_ref().encode(env),
                    self.0.lang.as_deref().encode(env),
                    self.0.scoped.encode(env),
                    self.0.module.as_deref().encode(env),
                    loc_to_term(env, &self.0.loc),
                    attrs_to_term(env, &self.0.attrs),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedCustomBlock<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::block_type().encode(env),
                    atoms::content().encode(env),
                    atoms::loc().encode(env),
                    atoms::attrs().encode(env),
                ],
                &[
                    self.0.block_type.as_ref().encode(env),
                    self.0.content.as_ref().encode(env),
                    loc_to_term(env, &self.0.loc),
                    attrs_to_term(env, &self.0.attrs),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedMacroArtifact<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        let mut keys = vec![
            atoms::kind().encode(env), atoms::name().encode(env), atoms::source()
            .encode(env), atoms::content().encode(env), atoms::start().encode(env),
            atoms::end_().encode(env)
        ];
        let mut values = vec![
            self.0.kind.as_str().encode(env), self.0.name.as_str().encode(env), self.0
            .source.as_str().encode(env), self.0.content.as_str().encode(env), self.0
            .start.encode(env), self.0.end.encode(env)
        ];
        if let Some(value) = self.0.module_code.as_ref() {
            keys.push(atoms::code().encode(env));
            values.push(value.as_str().encode(env));
        }
        Term::map_from_arrays(env, &keys, &values).unwrap()
    }
}
impl rustler::Encoder for EncodedTemplateCompileResult<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::code().encode(env),
                    atoms::preamble().encode(env),
                    atoms::helpers().encode(env),
                ],
                &[
                    self.code.encode(env),
                    self.preamble.encode(env),
                    self.helpers.encode(env),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedSsrCompileResult<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[atoms::code().encode(env), atoms::preamble().encode(env)],
                &[self.code.encode(env), self.preamble.encode(env)],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedParseSfcResult<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::template().encode(env),
                    atoms::script().encode(env),
                    atoms::script_setup().encode(env),
                    atoms::styles().encode(env),
                    atoms::custom_blocks().encode(env),
                ],
                &[
                    self
                        .descriptor
                        .template
                        .as_ref()
                        .map(|value| EncodedTemplateBlock(value).encode(env))
                        .unwrap_or_else(|| nil_term(env)),
                    self
                        .descriptor
                        .script
                        .as_ref()
                        .map(|value| EncodedScriptBlock(value).encode(env))
                        .unwrap_or_else(|| nil_term(env)),
                    self
                        .descriptor
                        .script_setup
                        .as_ref()
                        .map(|value| EncodedScriptBlock(value).encode(env))
                        .unwrap_or_else(|| nil_term(env)),
                    self
                        .descriptor
                        .styles
                        .iter()
                        .map(|value| EncodedStyleBlock(value).encode(env))
                        .collect::<Vec<Term<'a>>>()
                        .encode(env),
                    self
                        .descriptor
                        .custom_blocks
                        .iter()
                        .map(|value| EncodedCustomBlock(value).encode(env))
                        .collect::<Vec<Term<'a>>>()
                        .encode(env),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedCompileSfcResult<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::code().encode(env),
                    atoms::css().encode(env),
                    atoms::errors().encode(env),
                    atoms::warnings().encode(env),
                    atoms::template_hash().encode(env),
                    atoms::style_hash().encode(env),
                    atoms::script_hash().encode(env),
                    atoms::macro_artifacts().encode(env),
                ],
                &[
                    self.code_override.unwrap_or(self.result.code.as_str()).encode(env),
                    self.result.css.as_deref().encode(env),
                    self
                        .result
                        .errors
                        .iter()
                        .map(|value| EncodedSfcError::from(value).encode(env))
                        .collect::<Vec<Term<'a>>>()
                        .encode(env),
                    self
                        .result
                        .warnings
                        .iter()
                        .map(|value| EncodedSfcError::from(value).encode(env))
                        .collect::<Vec<Term<'a>>>()
                        .encode(env),
                    self.template_hash.as_deref().encode(env),
                    self.style_hash.as_deref().encode(env),
                    self.script_hash.as_deref().encode(env),
                    self
                        .result
                        .macro_artifacts
                        .iter()
                        .map(|value| EncodedMacroArtifact(value).encode(env))
                        .collect::<Vec<Term<'a>>>()
                        .encode(env),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedCssAstResult<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::ast().encode(env),
                    atoms::errors().encode(env),
                    atoms::warnings().encode(env),
                ],
                &[
                    self
                        .result
                        .ast
                        .as_ref()
                        .map(|value| encode_json_value(env, value))
                        .unwrap_or_else(|| nil_term(env)),
                    self
                        .result
                        .errors
                        .iter()
                        .map(|value| value.as_str().encode(env))
                        .collect::<Vec<Term<'a>>>()
                        .encode(env),
                    self
                        .result
                        .warnings
                        .iter()
                        .map(|value| value.as_str().encode(env))
                        .collect::<Vec<Term<'a>>>()
                        .encode(env),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedCssCompileResult<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::code().encode(env),
                    atoms::css_vars().encode(env),
                    atoms::errors().encode(env),
                    atoms::warnings().encode(env),
                    atoms::exports().encode(env),
                ],
                &[
                    self.result.code.as_str().encode(env),
                    self
                        .result
                        .css_vars
                        .iter()
                        .map(|value| value.as_str().encode(env))
                        .collect::<Vec<Term<'a>>>()
                        .encode(env),
                    self
                        .result
                        .errors
                        .iter()
                        .map(|value| value.as_str().encode(env))
                        .collect::<Vec<Term<'a>>>()
                        .encode(env),
                    self
                        .result
                        .warnings
                        .iter()
                        .map(|value| value.as_str().encode(env))
                        .collect::<Vec<Term<'a>>>()
                        .encode(env),
                    encode_css_exports(env, self.result.exports.as_ref()),
                ],
            )
            .unwrap()
    }
}
impl rustler::Encoder for EncodedBundleCssResult<'_> {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        Term::map_from_arrays(
                env,
                &[
                    atoms::code().encode(env),
                    atoms::errors().encode(env),
                    atoms::warnings().encode(env),
                    atoms::exports().encode(env),
                ],
                &[
                    self.result.code.as_str().encode(env),
                    self
                        .result
                        .errors
                        .iter()
                        .map(|value| value.as_str().encode(env))
                        .collect::<Vec<Term<'a>>>()
                        .encode(env),
                    self
                        .result
                        .warnings
                        .iter()
                        .map(|value| value.as_str().encode(env))
                        .collect::<Vec<Term<'a>>>()
                        .encode(env),
                    encode_css_exports(env, self.result.exports.as_ref()),
                ],
            )
            .unwrap()
    }
}
